name: Flask CI

On:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Print Debugging Information
      run: |
       echo "Python Version: $(python --version)"
       echo "Working directory: $(pwd)"
       echo "Contents of the working directory: $(ls -l)"
       echo "Contents of the site-packages: $(ls -l venv/lib/python*/site-packages)"

    - name: Run tests
      run: |  python test_hello.py

       
       
    
